intrinsic MDIsogenies(E::CrvEll[FldFin], p::RngIntElt) -> SeqEnum[MapSch]
{ Returns the p+1 elliptic curves that are p-isogenous to an initial E
  curve defined over a finite field
}
    assert IsPrime(p);
    //assert p ne 2;
    Fq := BaseRing(E);
    fp := DivisionPolynomial(E,p);
    Fqn := SplittingField(fp);
    Fq2n := RandomExtension(Fqn, 2);
    // this following line is to prevent a bug, see test_IsogeniesBugFix()
    xi := Roots(ChangeRing(fp,Fqn));
    xi := Roots(ChangeRing(fp,Fq2n));
    Eq2n := BaseChange(E,Fq2n);
    fE := DefiningEquation(Eq2n);
    yi := [Roots(UnivariatePolynomial(Evaluate(Evaluate(fE,3,1),1,x[1])))[1][1] : x in xi];
    Pi := [E(Fq2n) ! [xi[i][1],yi[i]] : i in [1..#xi]];
    //now Pi is a list with all torsion points

    R<X> := PolynomialRing(Fq2n);
    kernel_polynomials := {&*[X-(j*P)[1] : j in [1..Ceiling((p-1)/2)]] : P in Pi};
    isogenies := [PowerStructure(MapSch) | ];
    for f in kernel_polynomials do;
        Ef,phi := IsogenyFromKernel(Eq2n,f);

        Append(~isogenies,phi);
    end for;
    return isogenies;
end intrinsic;

intrinsic MDIsogeniesFast(E::CrvEll[FldFin], q::RngIntElt) -> List
{ One q-isogeny per orbit of the base field Frobenius on the q+1 subgroups of order q
  of E, as a list of tuples <phi, e, F1>: phi is defined over the field of definition L
  of its kernel, e = [L:K] is the size of the orbit, so that the e isogenies of an
  orbit are the Frobenius conjugates of phi and the e sum to q+1, and F1 is a field
  containing both K and L.

  Coerce points of E(K) into the domain of phi through F1, as
  Domain(phi) ! [BaseRing(Domain(phi)) ! (F1 ! c) : c in Eltseq(P)].  L is constructed
  as a subfield of F1 and magma does not in general register it as an extension of K,
  so neither L ! c nor phi(P) can be relied on.

  MDIsogenies works over the splitting field of the whole q-division polynomial, of
  degree up to (q^2-1)/2 over K; here every kernel is handled over its own field of
  definition, of degree at most q+1 over K.  On the degree 5 place of X_1(45) over GF(7)
  for which MDIsogenies needs 7114 seconds to give T_11, this takes 4.3 seconds.

  q must be an odd prime different from the characteristic.  For q = 2 use MDIsogenies:
  the kernel polynomial below is a product over 1 <= k <= (q-1)/2, which is empty.
}
    K := BaseRing(E);
    require IsPrime(q) and IsOdd(q) and q ne Characteristic(K) :
        "q must be an odd prime different from the characteristic";
    fq := DivisionPolynomial(E, q);
    factors := [t[1] : t in Factorization(fq)];
    // q does not divide the characteristic, so E[q] is etale and the x-coordinates of its
    // (q^2-1)/2 pairs {Q, -Q} of nonzero points are distinct
    assert &+[Degree(h) : h in factors] eq (q^2 - 1) div 2;
    a1, a2, a3, a4, a6 := Explode(aInvariants(E));
    unassigned := [true : h in factors];
    // a list, not a sequence: the isogenies of different orbits are defined over
    // different fields, so their tuples lie in different cartesian products
    isogenies := [* *];
    total := 0;
    for i in [1..#factors] do
        if not unassigned[i] then continue; end if;
        h := factors[i];
        // F1 = K(x1) for a root x1 of h, and F2 a field containing the matching y1
        if Degree(h) eq 1 then
            F1 := K; x1 := -Coefficient(h, 0)/Coefficient(h, 1);
        else
            F1 := ext<K | h>; x1 := F1.1;
        end if;
        PY<Y> := PolynomialRing(F1);
        ypol := Y^2 + (F1 ! a1*x1 + F1 ! a3)*Y
                    - (x1^3 + F1 ! a2*x1^2 + F1 ! a4*x1 + F1 ! a6);
        roots := Roots(ypol);
        if #roots gt 0 then
            F2 := F1; y1 := roots[1][1];
        else
            F2 := ext<F1 | 2>; y1 := Roots(PolynomialRing(F2) ! ypol)[1][1];
        end if;
        E2 := EllipticCurve([F2 | a1, a2, a3, a4, a6]);
        P1 := E2 ! [F2 ! x1, y1];
        assert q*P1 eq E2 ! 0 and P1 ne E2 ! 0;
        // the kernel polynomial of G = <P1>; the x-coordinates of the k*P1 lie in F1
        PX<X> := PolynomialRing(F1);
        g := &*[X - F1 ! ((k*P1)[1]) : k in [1..(q-1) div 2]];
        coeffs := Coefficients(g);
        // G is defined over the field generated by the coefficients of g, since a subgroup
        // of order q is determined by the set of x-coordinates of its nonzero points
        L := sub<F1 | coeffs cat [F1 ! K.1]>;
        assert Degree(L) mod Degree(K) eq 0;
        e := Degree(L) div Degree(K);
        // the factors of fq belonging to this orbit are the divisors of the K-norm of g
        norm := PX ! 1; conjugate := g;
        for j in [1..e] do
            norm *:= conjugate;
            conjugate := PX ! [c^#K : c in Coefficients(conjugate)];
        end for;
        assert conjugate eq g;  // the orbit has size e
        normK := PolynomialRing(K) ! [K ! c : c in Coefficients(norm)];
        assigned_degree := 0;
        for j in [1..#factors] do
            if unassigned[j] and IsDivisibleBy(normK, factors[j]) then
                unassigned[j] := false;
                assigned_degree +:= Degree(factors[j]);
            end if;
        end for;
        assert assigned_degree eq e*(q-1) div 2;
        EL := EllipticCurve([L ! (F1 ! a) : a in aInvariants(E)]);
        _, phi := IsogenyFromKernel(EL, PolynomialRing(L) ! [L ! c : c in coeffs]);
        Append(~isogenies, <phi, e, F1>);
        total +:= e;
    end for;
    assert total eq q + 1;
    return isogenies;
end intrinsic;
